// Backfill existing data/rankings/*.txt into D1 as approved 'legacy' rankings.
// Emits schema/seed-rankings.sql (applied via `wrangler d1 execute`).

import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadCatalogFromFs } from '../src/catalog-fs.ts';
import { Matcher } from '../src/matcher.ts';
import { parseRankings } from '../src/parse.ts';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const cat = loadCatalogFromFs(join(root, 'data'));
const matcher = new Matcher(cat);
const now = new Date().toISOString();

const q = (v: string | number | null | undefined): string =>
  v === null || v === undefined ? 'NULL' : typeof v === 'number' ? String(v) : `'${v.replace(/'/g, "''")}'`;

const stmts: string[] = ['-- Generated by scripts/backfill-txt.ts', "DELETE FROM ranking WHERE source = 'legacy';"];
let rankingIdSeq = 0;
let rankings = 0,
  items = 0;

const dir = join(root, 'data', 'rankings');
for (const file of readdirSync(dir).filter((f) => f.endsWith('.txt'))) {
  const text = readFileSync(join(dir, file), 'utf8');
  for (const parsed of parseRankings(text)) {
    const id = ++rankingIdSeq;
    // Heuristic: a big list ranks "everything" (scope=all); a short one is a
    // subset we can't infer a universe for (scope=custom).
    const scope = parsed.items.length >= 150 ? 'all' : 'custom';
    stmts.push(
      `INSERT INTO ranking (id, title, ranker_name, source, scope_type, scope_ref, note, created_at) VALUES ` +
        `(${id}, ${q(file.replace('.txt', ''))}, ${q(parsed.rankerName)}, 'legacy', ${q(scope)}, NULL, ${q('imported from ' + file)}, ${q(now)});`,
    );
    rankings++;
    const rows: string[] = [];
    parsed.items.forEach((item, i) => {
      const m = matcher.match(item);
      const songId = m.state === 'matched' ? m.songId : null;
      const customName = songId ? null : item.songText;
      rows.push(
        `(${id}, ${i + 1}, ${q(songId)}, ${q(customName)}, ${q(item.rawLine)}, ${q(m.via)}, ${m.score})`,
      );
      items++;
    });
    for (let i = 0; i < rows.length; i += 100) {
      stmts.push(
        `INSERT OR REPLACE INTO ranking_item (ranking_id, position, song_id, custom_name, raw_line, match_via, match_score) VALUES\n` +
          rows.slice(i, i + 100).join(',\n') +
          ';',
      );
    }
  }
}

const outPath = join(root, 'schema', 'seed-rankings.sql');
writeFileSync(outPath, stmts.join('\n') + '\n');
console.log(`Wrote ${outPath}: ${rankings} rankings, ${items} items`);
