// Generate schema/seed-events.sql: concert "legs" (grouped by concertId) and the
// union of each leg's setlist songs, from performance-info + performance-setlists.

import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const read = (f: string) => JSON.parse(readFileSync(join(root, 'data', f), 'utf8'));
const perf = read('performance-info.json') as any[];
const sets = read('performance-setlists.json') as Record<string, any>;

const q = (v: string | number | null | undefined): string =>
  v === null || v === undefined ? 'NULL' : typeof v === 'number' ? String(v) : `'${String(v).replace(/'/g, "''")}'`;

// group performances by concertId
const legs = new Map<string, any[]>();
for (const p of perf) {
  if (!p.concertId) continue;
  const k = String(p.concertId);
  if (!legs.has(k)) legs.set(k, []);
  legs.get(k)!.push(p);
}

const stripDay = (name: string | undefined): string =>
  (name ?? '').replace(/[\s（(]*(Day|DAY)[\s.]*\.?\s*\d+.*$/i, '').replace(/[\s（(]*(昼公演|夜公演).*$/, '').trim();

const setlistSongs = (perfId: string): string[] => {
  const sl = sets[perfId];
  const items = sl?.items ?? sl?.songs ?? [];
  return items.filter((i: any) => (i.type === 'song' || i.songId) && i.songId).map((i: any) => String(i.songId));
};

const eventRows: string[][] = [];
const eventSongRows: string[][] = [];
let legCount = 0,
  songLinks = 0;

for (const [concertId, days] of legs) {
  const union = new Set<string>();
  let hasAnySetlist = false;
  for (const d of days) {
    const songs = setlistSongs(String(d.id));
    if (songs.length) hasAnySetlist = true;
    songs.forEach((s) => union.add(s));
  }
  if (!hasAnySetlist || union.size === 0) continue; // only legs with real setlists
  legCount++;
  const dates = days.map((d) => d.date).filter(Boolean).sort();
  const seriesIds = [...new Set(days.flatMap((d) => (d.seriesIds ?? []).map(String)))];
  const first = days[0];
  eventRows.push([
    q(concertId),
    q(first.tourName),
    q(stripDay(first.performanceName ?? first.concertName) || first.tourName),
    q(first.venue),
    q(JSON.stringify(seriesIds)),
    q(dates[0]),
    q(dates[dates.length - 1]),
    String(days.length),
  ]);
  for (const songId of union) {
    eventSongRows.push([q(concertId), q(songId)]);
    songLinks++;
  }
}

function batch(table: string, cols: string[], rows: string[][]): string {
  const out: string[] = [];
  for (let i = 0; i < rows.length; i += 100)
    out.push(
      `INSERT OR REPLACE INTO ${table} (${cols.join(', ')}) VALUES\n` +
        rows.slice(i, i + 100).map((r) => `  (${r.join(', ')})`).join(',\n') +
        ';',
    );
  return out.join('\n');
}

const sql = [
  '-- Generated by scripts/build-events-sql.ts',
  'DELETE FROM event; DELETE FROM event_song;',
  batch('event', ['id', 'tour_name', 'name', 'venue', 'series_ids', 'date_start', 'date_end', 'day_count'], eventRows),
  batch('event_song', ['event_id', 'song_id'], eventSongRows),
  '',
].join('\n\n');

writeFileSync(join(root, 'schema', 'seed-events.sql'), sql);
console.log(`Wrote schema/seed-events.sql: ${legCount} events (legs), ${songLinks} event-song links`);
