// Generate schema/seed-catalog.sql from data/*.json:
// series, artist, song rows + song_match_key (null-on-collision) rows.

import { writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadCatalogFromFs } from '../src/catalog-fs.ts';
import { normalizeKey, normalizeStrict, phoneticToRomajiKey } from '../src/normalize.ts';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const cat = loadCatalogFromFs(join(root, 'data'));

const q = (v: string | null | undefined): string =>
  v === null || v === undefined ? 'NULL' : `'${String(v).replace(/'/g, "''")}'`;

function batchInsert(table: string, cols: string[], rows: string[][]): string {
  if (!rows.length) return '';
  const out: string[] = [];
  for (let i = 0; i < rows.length; i += 100) {
    const chunk = rows.slice(i, i + 100);
    out.push(
      `INSERT OR REPLACE INTO ${table} (${cols.join(', ')}) VALUES\n` +
        chunk.map((r) => `  (${r.join(', ')})`).join(',\n') +
        ';',
    );
  }
  return out.join('\n');
}

// series / artist / song
const seriesRows = cat.series.map((s) => [q(s.id), q(s.name), 'NULL', q(s.color)]);
const artistRows = cat.artists.map((a) => [q(a.id), q(a.name), q(a.englishName), 'NULL']);
const songRows = cat.songs.map((s) => [
  q(s.id),
  q(s.name),
  q(s.englishName),
  q(s.phoneticName),
  q(JSON.stringify(s.seriesIds)),
  q(cat.released.get(s.id)),
  q(JSON.stringify(s.artistIds)),
]);

// match keys with null-on-collision
const keyMap = new Map<string, { songId: string | null; source: string }>();
const add = (key: string, songId: string, source: string) => {
  if (!key) return;
  const cur = keyMap.get(key);
  if (!cur) keyMap.set(key, { songId, source });
  else if (cur.songId !== songId) cur.songId = null; // collision
};
for (const s of cat.songs) {
  add(normalizeKey(s.name), s.id, 'name');
  if (s.englishName) {
    add(normalizeStrict(s.englishName), s.id, 'en');
    add(phoneticToRomajiKey(s.englishName), s.id, 'romaji');
  }
  if (s.phoneticName) add(phoneticToRomajiKey(s.phoneticName), s.id, 'phonetic');
}
const keyRows = [...keyMap.entries()].map(([key, v]) => [q(key), q(v.source), q(v.songId)]);

const sql = [
  '-- Generated by scripts/build-catalog-sql.ts — do not edit by hand.',
  'DELETE FROM song_match_key;',
  batchInsert('series', ['id', 'name_jp', 'name_en', 'color'], seriesRows),
  batchInsert('artist', ['id', 'name_jp', 'name_en', 'series_ids'], artistRows),
  batchInsert('song', ['id', 'name_jp', 'name_en', 'phonetic', 'series_ids', 'released_on', 'artist_ids'], songRows),
  batchInsert('song_match_key', ['key', 'source', 'song_id'], keyRows),
  '',
].join('\n\n');

const outPath = join(root, 'schema', 'seed-catalog.sql');
writeFileSync(outPath, sql);
console.log(
  `Wrote ${outPath}: ${seriesRows.length} series, ${artistRows.length} artists, ${songRows.length} songs, ${keyRows.length} match keys`,
);
